# -*- coding: utf-8 -*-
"""FASTERRCNNTRAINNING

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eUQw2GLeGM5d6EVEXb8n2O0PuHm_Vpq_
"""

import torch

cd /content/drive/MyDrive

# !git clone https://github.com/jwyang/faster-rcnn.pytorch.git

cd /content/drive/MyDrive/faster-rcnn.pytorch

!git checkout -f pytorch-1.0

cd /content/drive/MyDrive/faster-rcnn.pytorch

# !mkdir data

cd /content/drive/MyDrive/faster-rcnn.pytorch/data

# !mkdir pretrained_model

cd /content/drive/MyDrive/faster-rcnn.pytorch

# !mkdir model

# !wget https://filebox.ece.vt.edu/~jw2yang/faster-rcnn/pretrained-base-models/resnet101_caffe.pth

!pip install -r requirements.txt

cd /content/drive/MyDrive/faster-rcnn.pytorch

!git clone https://github.com/pdollar/coco.git

cd coco/PythonAPI

!make

# !git clone https://github.com/pdollar/coco.git

cd /content/drive/MyDrive/faster-rcnn.pytorch/lib

!sh make.sh

cd /content/drive/MyDrive/faster-rcnn.pytorch/lib

!python setup.py build 
# build.py has sth wrong because from torch.utils.ffi import create_extension is old, so from torch.utils.cpp_extension import BuildExtension should be used
# this functions are in model/nums, roi_align, etc.

!pip install scipy==1.2.1

cd /content/drive/MyDrive/faster-rcnn.pytorch

#because of cache which can cause error#training and validation with +1 and -1 can cause error

!CUDA_VISIBLE_DEVICES=0 python trainval_net.py 	--dataset pascal_voc --net res50 \
							--epochs 100 --bs 1 --nw 4 --lr 1e-3 --lr_decay_step 8 --use_tfb \
							--mGPUs --cuda --o adam --bs 16

!nvcc --version

torch.cuda.is_available()

!python test_net.py --dataset pascal_voc --net res101 \
                   --checksession 1 --checkepoch 20 --checkpoint 465  \
                   --cuda --vis

